### ISSUE TITLE
Using NDTAMR for integrating a complex valued function

### ISSUE THREAD

**Issue by oroszl** [adamdempsey90/NDTAMR#2]
Hi, 
I was wondering if it is possible to use the package for integrating complex valued functions. 
- As far as I can tell from the code there is nothing specific preventing me from defining a data class holding complex data, is this true ?
- How can one access data points of the evaluated function on the grid ?

**Comment by adamdempsey90** [comment]
Hi,

You should in principle be able to use complex data via the method you described. To be safe you should probably separately store the real and imaginary components in their own arrays since the visualization / amr functions default to real arrays. 

There are several ways to access the data depending on what exactly you want to do. There are examples of how to convert slices of the tree into 2D numpy arrays in the visualization file Vis.py. You can also traverse the tree structure to find the cell that is located at the data coordinates you're interested in. 
One way to do this is to use the get_name( (x,y,z) ) method of the tree and then insert that name into the find(name) method of the tree to return the node pointing to your desired coordinates.

**Comment by oroszl** [comment]
@adamdempsey90 Thanks for your answer I think we can close this issue. I might have another, more technical one but will open a new thread for it.
